### ISSUE TITLE
无法登录后台管理

### ISSUE THREAD

**Issue by ulysseswolf** [476552238li/TP-Admin#1]
404 error
The requested URL /tp-admin/Public/login was not found on this server

**Comment by xiaoyao-work** [comment]
你是fork到本地的？还是在线的？可以具体说一下吗？我这边测试没有问题

**Comment by xiaoyao-work** [comment]
再次确认没有该问题，请确认你的重写是否开启。确认大小写问题

**Comment by jettyk** [comment]
我没有什么不能登陆的，另外关于fork我不太明白，应该是默认的

在 2015-05-04 16:26:18，"XiaoYao Li" notifications@github.com 写道：

再次确认没有该问题，请确认你的重写是否开启。确认大小写问题
