### ISSUE TITLE
Index/index查询 Menu目录where条目出错

### ISSUE THREAD

**Issue by bergsail** [476552238li/TP-Admin#2]
IndexAction.class.php 第六行
 $top_menu = $model->where( array( 'siteid' => $this->siteid, 'pid' => 0, 'status' => 1 ) )->order('sort desc...

node中没有siteid  可以把" 'siteid' => $this->siteid', " 去掉

**Comment by 476552238li** [comment]
谢谢！已经升级版本至2.0版本，请参考 https://github.com/476552238li/TP-Admin-V2.0/ 持续更新中！

**Comment by xiaoyao-work** [comment]
项目以全面迁移至 https://github.com/xiaoyao-work/TP-Admin

**Comment by xiaoyao-work** [comment]
项目以全面迁移至 https://github.com/xiaoyao-work/TP-Admin
