### ISSUE TITLE
普通管理员不能自己的修改密码

### ISSUE THREAD

**Issue by bergsail** [476552238li/TP-Admin#3]
ajax检测输入旧密码是否正确地时候，需要调用Changpwd/public_password_ajx，但是不同管理员没有这个方法的权限
解决： 添加配置 'NOT_AUTH_ACTION'    public_password_ajx

**Comment by bergsail** [comment]
Step1：见上
Step2：在修改密码(editor)节点上添加子节点、修改后显示（index）节点，Changpwd/index。然后给普通管理员这个节点的权限。--------在处理完step1，普通用户修改完自己的密码后，不能跳转页面，也是权限问题。step2通过添加节点和用户权限解决

**Comment by xiaoyao-work** [comment]
项目以全面迁移至 https://github.com/xiaoyao-work/TP-Admin
